repos:
-   repo: git@github.com:Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline', '--plugin','detect-secrets-plugins/occ_regex.py', '--word-list', '.secrets.ignore']
        additional_dependencies: ['pyahocorasick']
        exclude: .secrets.ignore
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --pattern, release/.*]
